version: "3"

services:
  nginx:
    build:
      context: ./conf
    volumes:
      - ./client:/var/www/client
      - ./server:/var/www/server
      - ./conf/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - kawai-network
    ports:
      - 80:80
    depends_on:
      - server_flask
      - client_react

  client_react:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    stdin_open: true
    networks:
      - kawai-network
    ports:
      - "3000:3000"

  server_flask:
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./server:/var/www/server
    environment:
      - FLASK_ENV=development
      - FLASK_APP=/var/www/server/app.py
      - FLASK_DEBUG=1
    networks:
      - kawai-network
    expose:
      - 5022
    ports:
      - "5022:5022"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    command: mongod --auth
    environment:
        MONGO_INITDB_ROOT_USERNAME: "admin"
        MONGO_INITDB_ROOT_PASSWORD: "password"
        MONGO_INITDB_DATABASE: kawaiapp
        MONGODB_DATA_DIR: /data/db
    volumes:
    - mongodbdata:/data/db
    networks:
    - kawai-network

networks:
  kawai-network:

volumes: 
  mongodbdata:
